# Generated by Django 5.0.7 on 2024-07-10 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.IntegerField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(max_length=250)),
                ('name_second', models.CharField(max_length=250)),
                ('telefon', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('registration', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
